### ISSUE TITLE
meta files

### ISSUE THREAD

**Issue by Hayao0819** [GunmaRamens/nixos-and-flakes-book-ja#5]
- [x] docs/.vitepress/config.ts (@rytst )
- [x] index.md (@Hayao0819 )
- [x] preface.md (@Hayao0819 )
- [ ] README.md
